### ISSUE TITLE
Replace images with incorrect sizes/proportions

### ISSUE THREAD

**Issue by lucpretti** [okfn/annual-report-2022#9]
![GQ](https://user-images.githubusercontent.com/8523847/213932524-b1547222-3a93-4a25-9db1-e7520e15190e.png)
![Kevin-Photo](https://user-images.githubusercontent.com/8523847/213932528-84f20499-3ec6-49b6-9488-3b3814e4337d.png)
![Lindsay](https://user-images.githubusercontent.com/8523847/213932529-f97167f9-8f01-41ab-9a34-038e5764938c.png)
![Melvin](https://user-images.githubusercontent.com/8523847/213932531-5cd4414b-1ade-455b-a0b9-f5a20b344b4d.png)
![Victoria](https://user-images.githubusercontent.com/8523847/213932532-b9301f54-777a-4496-9f2b-b4929d73b297.png)
![Zarena](https://user-images.githubusercontent.com/8523847/213932533-0adcc708-7d0e-4045-a362-b5118b3e28a4.png)
![bcn-meeting-low 1](https://user-images.githubusercontent.com/8523847/213932614-932fc389-d213-4d16-a4c5-acb932450eaa.png)
![PXL_20220512_131113140 1](https://user-images.githubusercontent.com/8523847/213932615-a345ec03-af9a-43eb-820a-680a2f41ece2.png)

**Comment by aivuk** [comment]
can you send the same pictures without the rounded corners? the rounded corner we are doing in css and if you add them to the picture we can't add the shadows using css

**Comment by lucpretti** [comment]
Here you go

![GQ](https://user-images.githubusercontent.com/8523847/214025937-93ec36ca-a509-44d3-ad03-f261d27925c7.jpeg)
![Kevin-Photo](https://user-images.githubusercontent.com/8523847/214025975-7b0b4bf8-6c8b-47c7-bf94-86806510ce16.jpeg)
![bcn-meeting-low](https://user-images.githubusercontent.com/8523847/214026199-51e10868-09a6-49ba-8ca9-951b7ba70101.jpg)
![PXL_20220512_131113140](https://user-images.githubusercontent.com/8523847/214026206-8fc5c8af-e736-4ebe-8e52-aee922fe520a.jpg)

![Lindsay](https://user-images.githubusercontent.com/8523847/214025979-52093ee8-2c9f-4563-8aee-415b68cd275e.jpeg)
![Melvin](https://user-images.githubusercontent.com/8523847/214025980-fc0b0d0c-848a-4bf1-9a72-a822ca8397e0.jpeg)
![Victoria](https://user-images.githubusercontent.com/8523847/214025982-23baee68-60ea-4858-bf5b-24d156707b33.jpeg)
![Zarena](https://user-images.githubusercontent.com/8523847/214025983-b6df9c8e-a592-4da7-be7e-8e236e7b2078.jpeg)

**Comment by lucpretti** [comment]
Images now resized:

![bcn-meeting-low](https://user-images.githubusercontent.com/8523847/214555387-8bf56dbe-817a-4baa-be24-5f24c2a3e8b1.jpg)
![FfCdJKmXEAEPGVu](https://user-images.githubusercontent.com/8523847/214555393-da695579-6a59-45f3-b353-5cbddb3f32a9.jpg)
![GQ](https://user-images.githubusercontent.com/8523847/214555395-3cc7ab9a-7e53-4368-ba26-413fd10e06d8.jpg)
![Kevin-Photo](https://user-images.githubusercontent.com/8523847/214555399-69a8f5e4-6423-45e7-8d07-423fa9fc78be.jpg)
![Lindsay](https://user-images.githubusercontent.com/8523847/214555401-981a2965-8141-4645-9104-83d196563b22.jpg)
![Melvin](https://user-images.githubusercontent.com/8523847/214555403-3035f2f0-1833-40bb-b3be-908b872fa3c6.jpg)
![PXL_20220512_131113140](https://user-images.githubusercontent.com/8523847/214555404-7267bc44-4ed3-462d-b88c-0d612215f840.jpg)
![Victoria](https://user-images.githubusercontent.com/8523847/214555406-ea48019a-976a-44f2-8748-3b4329d8c9e4.jpg)
![Zarena](https://user-images.githubusercontent.com/8523847/214555407-b22388e7-6183-47dd-995e-f7b129125294.jpg)
